const template = `
# How to use this project
This project is generated by the TS Starter Kit CLI.

# Project Structure
- **src/**: Contains the source code of the project.
- **tests/**: Contains the test files.

# How to dev
\`\`\`sh
# use npm
npm i
npm run dev

# use pnpm
pnpm i
pnpm dev

# use yarn
yarn i
yarn dev
\`\`\`
`;

export default template.trim() + "\n";
